### ISSUE TITLE
Error on first import

### ISSUE THREAD

**Issue by rmartinezgc** [ecampbell/moodle-booktool_wordimport#17] opened 2022-04-29 10:14 UTC
Good morning.

I just installed the pugin, I import the word document, it tells me that everything is ok but the book is still empty. What is the reason for this?

The Moodle version is 3.7.1 (Build: 20190708) and the plugin is 1.4.11 (Build: 2021083100)

Thank you.

Regards.

**Comment by rmartinezgc** [comment] 2022-04-29 11:15
Thank you for your quick answer.

In my case, my test document does have several "official" word headers as your video indicates.

Could you review the document I share with you? It's a simple document to test the import with headers and it doesn't work for me: [https://1drv.ms/w/s!Avf8NS5WJFHUa9Ys8doGLOj2oIc?e=rRgNXC](https://1drv.ms/w/s!Avf8NS5WJFHUa9Ys8doGLOj2oIc?e=rRgNXC)

On the other hand, if you could provide me with one that has worked for you, I could do the same test.

Sorry for the inconvenience.

Thank you.

**Comment by ecampbell** [comment] 2022-04-29 11:33
I download and imported your document fine into my test site at www.moodle2word.net (Book sandbox course). There is a possibility that if you are using a Spanish edition of Word, the heading names embedded into the Word file are in Spanish, and that this is causing the problem. The plugin is designed to handle this situation, but perhaps something is going wrong.  Can you email me a copy of the original file directly to help@moodle2word.net. Also try logging in to my test site [www.moodle2word.net](http://www.moodle2word.net/course/view.php?id=221) with the username and password **bookmaker**, and importing your file into a Book resource. If it works there, then there is something amiss in your installation.

**Comment by rmartinezgc** [comment] 2022-04-29 12:30
I just imported the original file into your platform and it doesn't work either. Maybe it's because of the language issue, as you say. I just mailed you the original file.

Thank you very much.

Regards.

**Comment by rmartinezgc** [comment] 2022-04-29 12:33
Sorry, in your platform worked fine

**Comment by ecampbell** [comment] 2022-04-29 13:46
You have reported an issue in the Book plugin bug tracker, but your  document imports correctly into a Book resource on the test server. Do you have the Book plugin installed on your own Moodle site? You should see a menu item "Import from Microsoft Word" 
![image](https://user-images.githubusercontent.com/852876/165956292-f3eec78c-73c8-4e88-875f-a1b5409f5252.png)
The [Atto button is a different plugin](https://moodle.org/plugins/atto_wordimport) which you can install, but requires that you also have the [Book plugin](https://moodle.org/plugins/booktool_wordimport) installed.

**Comment by rmartinezgc** [comment] 2022-05-02 06:10
Yes, I see the import menu import
![imagen](https://user-images.githubusercontent.com/3283956/166191494-24565701-7c47-40c7-97c6-cbbc9f4e7a00.png)

After that, I seems that everything is ok but nothing is imported
![imagen](https://user-images.githubusercontent.com/3283956/166191577-1d038e97-ef5c-4fd8-be88-cbac9935ff8f.png)

![imagen](https://user-images.githubusercontent.com/3283956/166191584-f6f0500e-dc25-441f-8dd3-d2b62abce5af.png)

I can see any error in the logs.

Are there any requirements needed for the import plugin to work?

**Comment by rmartinezgc** [comment] 2022-05-03 10:45
Any other idea?

**Comment by rmartinezgc** [comment] 2022-05-05 07:54
I have just sent you an email with the access credentials to our moodle so you can make the tests you consider appropriate.

Thank you very much.

Regards.

**Comment by ecampbell** [comment] 2022-08-03 17:16
Cannot reproduce this problem on a site that I can debug on, so closing.

**Comment by ecampbell** [comment] 2022-08-03 17:16
Cannot reproduce this problem on a site that I can debug on, so closing.

**Closed** 2022-08-03 17:16 UTC
